---
- name: Add group to simple_allow_groups line in /etc/sssd/sssd.conf
  hosts: all
  become: true
  tasks:
    - name: Add group to simple_allow_groups line
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^simple_allow_groups = '
        line: 'simple_allow_groups = Domain Admins,CofreAWS_Infra_admlocal{{ ("," + item) if item else "" }}'
        backrefs: yes
        state: present
      loop: "{{ lookup('ini', 'simple_allow_groups type=properties file=/etc/sssd/sssd.conf') | default([], true) }}"
      when: "'Domain Admins' in item"

    - name: Restart sssd service
      service:
        name: sssd
        state: restarted
