---
- name: Edit sssd.conf file
  hosts: your_linux_host
  become: true
  tasks:
    - name: Backup sssd.conf file
      copy:
        src: /etc/sssd/sssd.conf
        dest: /etc/sssd/sssd.conf.bkp
  
    - name: Edit sssd.conf file
      replace:
        path: /etc/sssd/sssd.conf
        regexp: 'simple_allow_groups\s*=\s*(.*)$'
        replace: 'simple_allow_groups = Domain Admins,CofreAWS_Infra_admlocal,\1'
      when: "'Domain Admins' in sssd_conf_content.stdout"

    - name: Add CofreAWS_Infra_admlocal to simple_allow_groups
      replace:
        path: /etc/sssd/sssd.conf
        regexp: 'simple_allow_groups\s*=\s*(.*)$'
        replace: 'simple_allow_groups = Domain Admins,CofreAWS_Infra_admlocal,\1'
      when: "'Domain Admins' in sssd_conf_content.stdout and 'CofreAWS_Infra_admlocal' not in sssd_conf_content.stdout"

    - name: Verify simple_allow_groups
      shell: cat /etc/sssd/sssd.conf | grep -E '^simple_allow_groups\s*='
      register: sssd_conf_content

    - name: Restart sssd service
      service:
        name: sssd
        state: restarted
