---
- name: Coletar informações do gateway em servidores Windows
  hosts: all
  become: false
  vars:
    ansible_remote_tmp: "C:\Temp\ansible"  # Definir o diretório temporário
  tasks:
    - name: Executar comando para identificar o gateway
      win_shell: Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.DefaultGateway -ne $null } | Select-Object -Property InterfaceAlias,IPAddress,DefaultGateway
      register: gateway_info

    - name: Exibir informações do gateway
      debug:
        var: gateway_info.stdout
