- name: Verifica e adiciona grupo no sssd.conf
  hosts: all
  become: yes

  tasks:
  - name: Faz backup do arquivo sssd.conf
    command: cp /etc/sssd/sssd.conf /etc/sssd/sssd.conf-$(date +%F-:%H:%M:%S)
    changed_when: false

  - name: Verifica se o grupo CofreAWS_Infra_admlocal existe
    shell: getent group CofreAWS_Infra_admlocal > /dev/null
    register: group_exists
    changed_when: false
    ignore_errors: true

  - name: Sai do script se o grupo já existe
    fail:
      msg: "O grupo CofreAWS_Infra_admlocal já existe."
    when: group_exists.rc == 0

  - name: Verifica se o arquivo sssd.conf existe
    stat:
      path: /etc/sssd/sssd.conf
    register: file_exists
    changed_when: false

  - name: Sai do script se o arquivo não existe
    fail:
      msg: "O arquivo /etc/sssd/sssd.conf não existe."
    when: not file_exists.stat.exists

  - name: Verifica se já existe a linha que contém "simple_allow_groups"
    shell: grep -q "simple_allow_groups" "/etc/sssd/sssd.conf"
    register: simple_allow_groups_exists
    changed_when: false

  - name: Adiciona o grupo no sssd.conf
    lineinfile:
      path: /etc/sssd/sssd.conf
      line: "simple_allow_groups = Domain Admins,CofreAWS_Infra_admlocal"
    when: not simple_allow_groups_exists.rc == 0
    notify: Restart sssd

  - name: Verifica se o grupo já está na lista
    shell: grep -q "simple_allow_groups.*Domain Admins.*,.*CofreAWS_Infra_admlocal.*" "/etc/sssd/sssd.conf"
    register: group_in_list
    changed_when: false
    when: simple_allow_groups_exists.rc == 0

  - name: Adiciona o grupo na lista existente
    replace:
      path: /etc/sssd/sssd.conf
      regexp: 'simple_allow_groups = \(.*Domain Admins.*\)$'
      replace: '\0,CofreAWS_Infra_admlocal'
    when: not group_in_list.rc == 0
    notify: Restart sssd

  - name: Adiciona o novo grupo diretamente
    replace:
      path: /etc/sssd/sssd.conf
      regexp: '^simple_allow_groups =\s*$'
      replace: 'simple_allow_groups = CofreAWS_Infra_admlocal'
    when: not group_in_list.rc == 0 and simple_allow_groups_exists.rc == 0
    notify: Restart sssd

  handlers:
  - name: Restart sssd
    systemd:
      name: sssd.service
      state: restarted
