---
- name: Testar conectividade com 8.8.8.8
  hosts: all
  tasks:
    - name: Executar 20 pings para 8.8.8.8
      command: ping -c 20 8.8.8.8
      register: ping_result

    - name: Mostrar o resultado do ping
      debug:
        msg: "{{ ping_result.stdout }}"