---
- name: Atualiza, reinicia e verifica serviços em qualquer host
  hosts: all
  become: true
  vars:
    servicos_criticos:
      - postgresql-13.service
      - zabbix-server.service
      - zabbix-agent
      - httpd
      - sssd
      - sshd

  tasks:
    - name: Atualiza pacotes do sistema
      dnf:
        name: "*"
        state: latest
      register: atualizacao

    - name: Define flag de reboot se houve atualizações
      set_fact:
        reboot_necessario: true
      when: atualizacao.changed

    - name: Reinicia o sistema se necessário
      reboot:
        msg: "Reiniciando após atualização de pacotes"
        reboot_timeout: 600
        post_reboot_delay: 30
      when: reboot_necessario is defined and reboot_necessario

    - name: Aguarda o host voltar após o reboot
      wait_for_connection:
        timeout: 300
      when: reboot_necessario is defined and reboot_necessario

    - name: Coleta informações sobre todos os serviços
      service_facts:

    - name: Inicia serviços se estiverem parados ou falharam
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ servicos_criticos }}"
      when: >
        ansible_facts.services[item] is defined and
        ansible_facts.services[item].state in ['stopped', 'failed']
